### ISSUE TITLE
extra space at the bottom part of the content

### ISSUE THREAD

**Issue by chipcerio** [robertlevonyan/materialExpansionPanel#1]
Hi, thanks for this solution. It works for the most part. I followed what's on the README but this one is not working for me. Did I miss something?

Cheers

**Comment by robertlevonyan** [comment]
Hi. Can you share your code?

**Comment by chipcerio** [comment]
Sure.  Here's the code for `content_view.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:paddingLeft="56dp"
        android:id="@+id/textView2"
        android:layout_width="0dp"
        android:layout_height="48dp"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="16dp"
        android:drawablePadding="16dp"
        android:gravity="center_vertical"
        android:text="TextView"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:paddingLeft="56dp"
        android:id="@+id/textView3"
        android:layout_width="0dp"
        android:layout_height="48dp"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="16dp"
        android:gravity="center_vertical"
        android:text="TextView"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView2" />

    <TextView
        android:paddingLeft="56dp"
        android:id="@+id/textView4"
        android:layout_width="0dp"
        android:layout_height="48dp"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="16dp"
        android:gravity="center_vertical"
        android:text="TextView"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView3" />

    <TextView
        android:paddingLeft="56dp"
        android:id="@+id/textView5"
        android:layout_width="0dp"
        android:layout_height="48dp"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="16dp"
        android:gravity="center_vertical"
        android:text="TextView"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView4" />
</android.support.constraint.ConstraintLayout>
```

and here's the code for `activity_main.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.chipcerio.expansionpanel.MainActivity">

    <com.robertlevonyan.views.expandable.Expandable
        android:id="@+id/expandable"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:exp_animateExpand="true">
        <include
            android:id="@+id/header"
            layout="@layout/header_view" />

        <include
            android:id="@+id/content"
            layout="@layout/content_view" />
    </com.robertlevonyan.views.expandable.Expandable>

</android.support.constraint.ConstraintLayout>
```

**Comment by robertlevonyan** [comment]
Can you also share a screenshot?

**Comment by qalekop** [comment]
Hi Robert! Nice work, thanks a lot for your Expandable! Unfortunately, there's really an extra space at the bottom of the body. I believe it's because of _collapsedViewHeight_ added at line #122:

expandableViewHeight = expandableView.getMeasuredHeight() **+ collapsedViewHeight**;

**Comment by touficbatache** [comment]
Any examples on how `header_view.xml` may look like?

**Comment by robertlevonyan** [comment]
it depends on you, you can create your own design

**Comment by robertlevonyan** [comment]
@qalekop that is for building view with exact sizes.

**Comment by hemanth2k13** [comment]
I'm facing same issue. It's not wrapping content. There is little extra space at the bottom.
![screenshot_2018-02-07-16-14-15](https://user-images.githubusercontent.com/20104424/35912369-689c40c0-0c22-11e8-8d2c-670120d81b6c.png)

********Header*******

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal">
    <com.krazybee.commons.android.widgets.customviews.PrimaryTextView
        android:id="@+id/txt_cash_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginLeft="16dp"
        android:layout_marginStart="16dp"
        android:layout_marginTop="8dp"
        android:text="CASHBACK"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.krazybee.commons.android.widgets.customviews.SecondaryTextView
        android:id="@+id/txt_cash_subtitle"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginLeft="16dp"
        android:layout_marginStart="16dp"
        android:layout_marginTop="8dp"
        android:textColor="@color/grey_a9"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toEndOf="@+id/txt_cash_title"
        app:layout_constraintTop_toTopOf="parent" />

</LinearLayout>

******Content******
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <RelativeLayout
        android:id="@+id/cask_back_slider_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_horizontal_margin">

        <com.krazybee.commons.android.widgets.customviews.SecondaryTextView
            android:id="@+id/cash_back_seekbar_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_toLeftOf="@+id/tv_widget_info_seek_bar_progress_info"
            android:layout_toStartOf="@+id/tv_widget_info_seek_bar_progress_info"
            android:maxLines="1"
            android:text="CASHBACK AMOUNT"
            android:textColor="@color/black"/>

        <com.krazybee.commons.android.widgets.customviews.PrimaryTextView
            android:id="@+id/cash_back_seekbar_status"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toLeftOf="@+id/tv_static_info_months"
            android:layout_toStartOf="@+id/tv_static_info_months"
            android:maxLines="1"
            android:textColor="@color/emi_color" />

        <com.krazybee.commons.android.widgets.customviews.PrimaryTextView
            android:id="@+id/tv_static_info_months"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toLeftOf="@+id/iv_tenure_tooltip"
            android:layout_toStartOf="@+id/iv_tenure_tooltip"
            android:maxLines="1"
            android:textColor="@color/emi_color" />

        <ImageView
            android:id="@+id/iv_tenure_tooltip"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="@dimen/spacing"
            android:layout_marginStart="@dimen/spacing"
            android:layout_toLeftOf="@+id/tv_static_info_emi"
            android:layout_toStartOf="@+id/tv_static_info_emi"
            android:background="@drawable/ic_tooltip"
            android:contentDescription="@string/empty_image"
            android:visibility="gone" />

        <com.krazybee.commons.android.widgets.customviews.PrimaryTextView
            android:id="@+id/tv_static_info_emi"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:maxLines="1"
            android:text="  "
            android:textColor="@color/emi_color"
            android:textSize="@dimen/secondary_text_label_size"
            tools:ignore="HardcodedText" />

        <com.krazybee.seekbar.DiscreteSeekBar
            android:id="@+id/summary_points_slider"
            android:layout_marginTop="16dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="@dimen/min_widget_padding"
            android:paddingTop="@dimen/min_widget_padding"
            app:dsb_allowTrackClickToDrag="true"
            app:dsb_indicatorColor="@color/colorPrimary"
            app:dsb_indicatorElevation="0dp"
            app:dsb_min="1"
            app:dsb_progressColor="@color/seek_bar_prog_color"
            app:dsb_rippleColor="@color/seek_bar_prog_color" />

    </RelativeLayout>

</LinearLayout>

*********fragment.xml********

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.robertlevonyan.views.expandable.Expandable
        android:id="@+id/coupon_expandable_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:elevation="4dp">

        <include
            android:id="@+id/header"
            layout="@layout/content_v1_coupon_header" />

        <include
            android:id="@+id/content"
            layout="@layout/content_v1_coupon_layout" />

    </com.robertlevonyan.views.expandable.Expandable>

    <com.robertlevonyan.views.expandable.Expandable
        android:id="@+id/cash_expandable_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginTop="2dp"
        android:elevation="4dp">

        <include
            android:id="@+id/header"
            layout="@layout/content_v1_cashback_header" />

        <include
            android:id="@+id/content"
            layout="@layout/content_v1_cashback_layout" />
    </com.robertlevonyan.views.expandable.Expandable>

</LinearLayout>

**Comment by pfieffer** [comment]
Yes. I am having the same issue. There is an extra space below the content.
Plus is there a way to disable the expandable icon on the Top Right. I tried `setIcon(null)` but no luck.

**Comment by touficbatache** [comment]
@pfieffer Try this, I am using it in my app: https://github.com/florent37/ExpansionPanel

**Comment by robertlevonyan** [comment]
@pfieffer please share a screenshot.
The icon is per the material design guides

**Comment by robertlevonyan** [comment]
Is that space in recyclerview?

**Comment by pfieffer** [comment]
Never mind about the icon.
But yes, I am using the expandable in a recycler view. Everything seems perfect except the space underneath.

**Comment by robertlevonyan** [comment]
Is the issue still appears?
