### ISSUE TITLE
Max height issue

### ISSUE THREAD

**Issue by alexdiostia** [robertlevonyan/materialExpansionPanel#2]
Hi
the panel is really great ! sadly i face some issue as the inner ChipGroup doesn't grow as it does without this ExpansionPanel...
when adding a number of Chips inside the ChipGroup , i can't see more than the 1st line of chips ...

i know i didn't use the include, but that seemed to work as below...

anything i miss ?
thanks a lot !

my xml:

<com.robertlevonyan.views.expandable.Expandable
                android:id="@+id/expandable"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="10dp"
                app:exp_backgroundColor="@color/colorPrimary"
                app:exp_headerBackgroundColor="@android:color/white"
                app:layout_constrainedHeight="false">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="labels" />

                <com.google.android.material.chip.ChipGroup
                    android:id="@+id/chipslayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">

                </com.google.android.material.chip.ChipGroup>

            </com.robertlevonyan.views.expandable.Expandable>

**Comment by robertlevonyan** [comment]
maybe the `ChipGroup` is aligning it's child views in one line?
