### ISSUE TITLE
Problem with dynamic resizing

### ISSUE THREAD

**Issue by sueml** [robertlevonyan/materialExpansionPanel#4]
First, thank you for the solution. I am enjoying using it, but it looks like there is a bug related to dynamic resizing.
When the content view has child components that resizes automatically, like multiline TextInputEditText or RecyclerView, the panel expanded is not automatically resized, hiding its child components. I can't call the expand method programatically because it's a private method.
Can you help me?
Thank you!

**Comment by robertlevonyan** [comment]
Thanks for writing. I'll create an update and make that function public so you can use it. Then I'll close this issue
