### ISSUE TITLE
Library code includes app icons

### ISSUE THREAD

**Issue by strongville** [robertlevonyan/materialExpansionPanel#7]
The library build includes app icons, which makes compilation fail for the project which is included into, because of a manifest merger error, as shown below:

```
C:\Users\Guillermo\...\app\src\main\AndroidManifest.xml:42:9-41 Error:
	Attribute application@icon value=(@mipmap/...) from AndroidManifest.xml:42:9-41
	is also present at [com.robertlevonyan.view:MaterialExpansionPanel:2.0.8] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:39:5-244:19 to override.
C:\Users\Guillermo\...\app\src\main\AndroidManifest.xml:45:9-46 Error:
	Attribute application@roundIcon value=(@mipmap/...) from AndroidManifest.xml:45:9-46
	is also present at [com.robertlevonyan.view:MaterialExpansionPanel:2.0.8] AndroidManifest.xml:15:9-54 value=(@mipmap/ic_launcher_round).
	Suggestion: add 'tools:replace="android:roundIcon"' to <application> element at AndroidManifest.xml:39:5-244:19 to override.
```
Icons shouldn't be included if the project is an Android libary.

*Workaround*: If you're using this library, and you're affected with this issue, you have to add the following line to your AndroidManifest.xml in your ```<application />``` node: ```tools:replace="android:icon,android:roundIcon"```

**Comment by klaszlo8207** [comment]
+1 for this, how to fix?

**Comment by klaszlo8207** [comment]
> tools:replace="android:icon,android:roundIcon"

If I add this, then my icon just turning to my app "Screenshot"!

**Comment by MairwunNx** [comment]
@strongville well, your solution didn't works for me, but thanks for creating this issue, because I was have a thoughts it's my problem

Have a nice coding week

**Comment by robertlevonyan** [comment]
please use the latest version
