### ISSUE TITLE
Build error with custom app icon name

### ISSUE THREAD

**Issue by omkar-tenkale** [robertlevonyan/materialExpansionPanel#9]
```
Manifest merger failed : Attribute application@icon value=(@drawable/myappicon) from AndroidManifest.xml:18:9-57
	is also present at [com.robertlevonyan.view:MaterialExpansionPanel:2.0.10] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:15:5-74:19 to override.
```

After adding 'tools:replace="android:icon"' to manifest,build throws another error
`
P:\myproject\app\build\intermediates\packaged_manifests\debug\AndroidManifest.xml:23: AAPT: error: resource mipmap/ic_launcher_round (aka com.myapp:mipmap/ic_launcher_round) not found.
    `

**Comment by robertlevonyan** [comment]
are you sure this is connected with this lib?

**Comment by robertlevonyan** [comment]
Please upgrade to the latest version 2.0.10

**Comment by omkar-tenkale** [comment]
Yup it was indeed  related to this lib
